services:
  app:
    container_name: app 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    networks:
      - app-network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"    
      - "443:443"  
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
