name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker compose -f docker-compose.yml build  # Build the images defined in your Docker Compose file
          docker compose -f docker-compose.yml push   # Optional: Push the images to your registry if needed

      - name: Access Server and Deploy
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.SERVER_ADDRESS }} -p ${{ secrets.SSH_PORT }} "
          echo ✅ SSH connection successful &&
          echo ✅ Changing directory to /www/GoCrudChallange &&
          cd /www/GoCrudChallange &&
          echo ✅ Pulling latest code from GitHub &&
          git pull https://${{ secrets.TOKEN }}@github.com/Mahider-T/GoCrudChallange.git main &&
          echo ✅ Stopping and removing running containers &&
          docker compose -f docker-compose.yml down &&  # Stop and remove current containers
          echo ✅ Starting Docker Compose services &&
          docker compose -f docker-compose.yml up -d --remove-orphans &&  # Start services in detached mode
          echo ✅ Deployed successfully &&
          exit"
